export const figmaAssets = {
  ball1: '/assets/ball-1.svg',
  ball2: '/assets/ball-2.svg',
  ball3: '/assets/ball-3.svg',
  ball4: '/assets/ball-4.svg',
  ball5: '/assets/ball-5.svg',
  ball6: '/assets/ball-6.svg',
  ball7: '/assets/ball-7.svg',
  ball8: '/assets/ball-8.svg',
  ball9: '/assets/ball-9.svg',
  ball10: '/assets/ball-10.svg',
  ball11: '/assets/ball-11.svg',
  machine: '/assets/machine.svg',
  handle: '/assets/handle.svg',
  transitionStar: '/assets/transition-star.svg',
  bean1: '/assets/bean-1.svg',
  bean2: '/assets/bean-2.svg',
  bean3: '/assets/bean-3.svg',
} as const;
